tags:
    - name: Admin
      description: |
        Manage Admin Operations
        
    - name: Company
      description: |
        Manage Company Operations
  
  paths:
    #Endpoint to create new admin
    /admin:
      #Post Operation
      post:
        tags:
          - Admin
  
        summary: Create an Admin to get token
  
        requestBody:
          description: A JSON object containing registration information
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
  
        responses:
          "201":
            description: Successful operation
            content:
              application/json:
                schema:
                  type: object
                  required:
                    - message
                    - status
                    - data
                  properties:
                    message:
                      type: string
                    status:
                      type: string
                    data:
                      type: object
                      properties:
                        apiKey:
                          type: string
          "400":
            description: Bad request error
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/ErrorResponse"
    
          "422":
            description: Validation error
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/ErrorResponse"
  
    #Endpoint to get admin details
    /admin/{adminId}:
      #GET Operation
      get:
        tags:
          - Admin
  
        summary: Get one Admin
  
        responses:
          "200":
            description: Successful operation
            content:
              application/json:
                schema:
                  type: object
                  required:
                    - message
                    - status
                    - data
                  properties:
                    message:
                      type: string
                    status:
                      type: string
                    data:
                      type: array
                      items:
                        $ref: "#/components/schemas/Admin"
  
          "400":
            description: Bad request error
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/ErrorResponse"
  
          "401":
            description: Authorization Error
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/ErrorResponse"
  
          "422":
            description: Validation error
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/ErrorResponse"

    #Endpoint to get admin api key
    /admin/{adminId}/key:
      #GET Operation
      get:
        tags:
          - Admin
  
        summary: Get Admin api key
  
        responses:
          "200":
            description: Successful operation
            content:
              application/json:
                schema:
                  type: object
                  required:
                    - message
                    - status
                    - data
                  properties:
                    message:
                      type: string
                    status:
                      type: string
                    data:
                      type: object
                      properties:
                        apiKey:
                          type: string
  
          "400":
            description: Bad request error
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/ErrorResponse"
  
          "401":
            description: Authorization Error
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/ErrorResponse"
  
          "422":
            description: Validation error
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/ErrorResponse"
  
    #Endpoint to get company profile
    /company/{symbol}/profile:
      #GET operation
      get:
        tags:
          - Company
  
        summary: Gets company profile and miscellaneous data
  
        security:
          - Bearer: []
  
        requestBody:
          description: none
          required: true
          content: none
  
          responses:
            "201":
              description: Successful operation
              content:
              application/json:
                schema:
                  type: object
                  required:
                    - message
                    - status
                    - data
                  properties:
                    message:
                      type: string
                    status:
                      type: string
                    data:
                      type: object
                      properties:
                        fullname:
                          type: string
                        email:
                          type: string
                        role:
                          type: string
            "401":
              description: Authorization Error
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/ErrorResponse"
  
            "400":
              description: Bad request error
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/ErrorResponse"
  
            "422":
              description: Validation error
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/ErrorResponse"
  
  components:
    #-------------------------------
    # Reusable schemas (data models)
    #-------------------------------
    schemas:
      Admin:
        type: object
        required:
          - email
        properties:
          email:
            type: string
          AdminId:
            type: string

  
      ErrorResponse: # Can be referenced as '#/components/schemas/Error'
        type: object
        required:
          - status
          - error
          - data
        properties:
          status:
            type: string
          error:
            type: string
          data:
            type: array
            items:
              type: string
            example: []
  
    #-------------------------------
    # Reusable operation parameters
    #-------------------------------
    parameters:
      organizationIdParam: # Can be referenced via '#/components/parameters/organizationIdParam'
        in: path
        name: organizationId
        description: String ID of the organization
        required: true
        schema:
          type: string
  
      msAdminIdParam: # Can be referenced via '#/components/parameters/msAdminIdParam'
        in: path
        name: msAdminId
        description: String ID of the Microservice Admin
        required: true
        schema:
          type: string
  